# Generated by Django 6.0.7 on 2026-07-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_itemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qr_code',
        ),
    ]
