# Generated by Django 6.0.7 on 2026-08-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_duplicate_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='finder_returned_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='owner_returned_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
