# Generated by Django 6.0.7 on 2026-08-22 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_options_alter_user_role_administrator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='user_permissions',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('match', 'Match Found'), ('approved', 'Report Approved'), ('rejected', 'Report Rejected'), ('message', 'New Message'), ('claim', 'Claim Update'), ('reputation', 'Reputation / Points'), ('badge', 'Badge Unlocked'), ('rating', 'Rating')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('finder', 'Finder'), ('admin', 'Admin')], default='owner', max_length=10),
        ),
        migrations.CreateModel(
            name='FinderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finder Rating',
                'verbose_name_plural': 'Finder Ratings',
                'db_table': 'finder_ratings',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'item')},
            },
        ),
        migrations.CreateModel(
            name='FinderReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('successful_returns', models.IntegerField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('rating_sum', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finder Reputation',
                'verbose_name_plural': 'Finder Reputations',
                'db_table': 'finder_reputation',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('FOUND_REPORT', 'Found Item Report'), ('SUCCESSFUL_RETURN', 'Successful Return'), ('POSITIVE_RATING', 'Positive Owner Rating'), ('MILESTONE_BONUS', 'Milestone Bonus'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('PENALTY', 'Penalty')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='api.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'db_table': 'point_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_returns', models.IntegerField(default=1)),
                ('icon', models.CharField(default='🏅', max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'db_table': 'user_badges',
                'ordering': ['required_returns'],
                'unique_together': {('user', 'badge_key')},
            },
        ),
        migrations.DeleteModel(
            name='AdminAuditLog',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
