# Generated by Django on 2026-08-28

from django.db import migrations, models

def migrate_user_roles(apps, schema_editor):
    User = apps.get_model('api', 'User')
    User.objects.filter(role__in=['owner', 'finder']).update(role='user')

def reverse_user_roles(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_administrator_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.RunPython(migrate_user_roles, reverse_user_roles),
    ]
