# Generated by Django 6.0.7 on 2026-08-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_restore_permanent_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('finder', 'Finder'), ('admin', 'Admin'), ('user', 'User')], default='owner', max_length=10),
        ),
    ]
