# Generated by Django 6.0.7 on 2026-08-29 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='admin_verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes on report credibility, identifying details, or reason for rejection.'),
        ),
        migrations.AddField(
            model_name='item',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
