# Generated by Django 6.0.7 on 2026-08-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_item_admin_verification_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
