# Generated by Django 6.0.7 on 2026-08-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_item_verification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='admin_verification_notes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='verified_by',
        ),
    ]
