# Generated by Django 6.0.7 on 2026-09-01 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_item_admin_verification_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_reports', to='api.item', verbose_name='Linked Lost Item'),
        ),
    ]
