# Generated by Django 6.0.7 on 2026-09-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_item_parent_item'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_item__isnull', False), ('type', 'found')), fields=('user', 'parent_item'), name='unique_finder_report_per_owner_item'),
        ),
    ]
