# Generated by Django 6.0.7 on 2026-09-14 04:11

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_item_unique_finder_report_per_owner_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Finder',
            fields=[
            ],
            options={
                'verbose_name': 'Finder',
                'verbose_name_plural': 'Finders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='has_unique_identifier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='identifier_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='item',
            name='identifier_masked',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='identifier_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='item_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='physical_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='item',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='private_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='item',
            name='secondary_color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('potential_match', 'Potential Match Found'), ('under_verification', 'Under Verification'), ('verification_required', 'Verification Required'), ('additional_proof_required', 'Additional Proof Required'), ('multiple_possible_owners', 'Multiple Possible Owners'), ('verified_match', 'Verified Match'), ('verification_failed', 'Verification Failed'), ('contact_allowed', 'Contact Allowed'), ('return_in_progress', 'Return In Progress'), ('returned', 'Returned'), ('closed', 'Closed')], default='unverified', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('phone', 'Mobile Phone'), ('laptop', 'Laptop'), ('wallet', 'Wallet'), ('bag', 'Bag / Backpack'), ('keys', 'Keys'), ('documents', 'Documents / ID Card'), ('watch', 'Watch'), ('jewelry', 'Jewelry'), ('headphones', 'Earbuds / Headphones'), ('book', 'Books / Notes'), ('clothing', 'Clothing / Apparel'), ('electronics', 'Electronics / Gadgets'), ('other', 'Other Item'), ('id_card', 'ID Card')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('match', 'Match Found'), ('verification', 'Verification Update'), ('approved', 'Report Approved'), ('rejected', 'Report Rejected'), ('message', 'New Message'), ('claim', 'Claim Update'), ('reputation', 'Reputation / Points'), ('badge', 'Badge Unlocked'), ('rating', 'Rating')], max_length=20),
        ),
        migrations.CreateModel(
            name='PotentialMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0)),
                ('confidence_level', models.CharField(choices=[('high', 'High Confidence Match'), ('medium', 'Medium Confidence Match'), ('low', 'Low Confidence Match')], default='medium', max_length=20)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('candidate_evidence', models.JSONField(blank=True, default=dict)),
                ('evidence_strength', models.CharField(choices=[('strong_identifier', 'Strong Identifier (Serial/IMEI/Asset Tag)'), ('distinctive_features', 'Distinctive Physical Characteristics / Private Features'), ('generic_candidate', 'Generic Candidate (Common Attributes Only)')], default='generic_candidate', max_length=30)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('potential_match', 'Potential Match Found'), ('under_verification', 'Under Verification'), ('verification_required', 'Verification Required'), ('additional_proof_required', 'Additional Proof Required'), ('multiple_possible_owners', 'Multiple Possible Owners'), ('verified_match', 'Verified Match'), ('verification_failed', 'Verification Failed'), ('contact_allowed', 'Contact Allowed'), ('return_in_progress', 'Return In Progress'), ('returned', 'Returned'), ('closed', 'Closed')], default='potential_match', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_potential_matches', to='api.item')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_potential_matches', to='api.item')),
            ],
            options={
                'verbose_name': 'Potential Match',
                'verbose_name_plural': 'Potential Matches',
                'db_table': 'potential_matches',
                'ordering': ['-similarity_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('potential_match', 'Potential Match Found'), ('under_verification', 'Under Verification'), ('verification_required', 'Verification Required'), ('additional_proof_required', 'Additional Proof Required'), ('multiple_possible_owners', 'Multiple Possible Owners'), ('verified_match', 'Verified Match'), ('verification_failed', 'Verification Failed'), ('contact_allowed', 'Contact Allowed'), ('return_in_progress', 'Return In Progress'), ('returned', 'Returned'), ('closed', 'Closed')], default='under_verification', max_length=30)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('verification_summary', models.TextField(blank=True, default='')),
                ('is_contact_allowed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finder_verifications', to=settings.AUTH_USER_MODEL)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_verification_requests', to='api.item')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_verification_requests', to='api.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_verifications', to=settings.AUTH_USER_MODEL)),
                ('potential_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='api.potentialmatch')),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'db_table': 'verification_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(max_length=40)),
                ('evidence_key', models.CharField(max_length=100)),
                ('submitted_value', models.TextField(blank=True, default='')),
                ('submitted_image', models.ImageField(blank=True, null=True, upload_to='verification_evidence/')),
                ('is_blind', models.BooleanField(default=True)),
                ('match_result', models.CharField(default='pending', max_length=20)),
                ('discriminative_weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_evidence', to=settings.AUTH_USER_MODEL)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_submissions', to='api.verificationrequest')),
            ],
            options={
                'verbose_name': 'Verification Evidence',
                'verbose_name_plural': 'Verification Evidence',
                'db_table': 'verification_evidence',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='potentialmatch',
            constraint=models.UniqueConstraint(fields=('lost_item', 'found_item'), name='unique_potential_match_pair'),
        ),
    ]
