# Generated by Django 6.0.7 on 2026-09-14 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_admin_finder_owner_item_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(default=0)),
                ('matched_reasons', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matched Item',
                'verbose_name_plural': 'Matched Items',
                'db_table': 'matched_items',
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='potentialmatch',
            name='unique_potential_match_pair',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='potential_match',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='finder',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='found_item',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='lost_item',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='owner',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='physical_attributes',
            new_name='category_attributes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='has_unique_identifier',
        ),
        migrations.RemoveField(
            model_name='item',
            name='identifier_hash',
        ),
        migrations.RemoveField(
            model_name='item',
            name='identifier_masked',
        ),
        migrations.RemoveField(
            model_name='item',
            name='identifier_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='private_attributes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='verification_status',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('phone', 'Phone'), ('keys', 'Keys'), ('bag', 'Bag'), ('id_card', 'ID Card'), ('documents', 'Documents'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('match', 'Match Found'), ('approved', 'Report Approved'), ('rejected', 'Report Rejected'), ('message', 'New Message'), ('claim', 'Claim Update'), ('reputation', 'Reputation / Points'), ('badge', 'Badge Unlocked'), ('rating', 'Rating')], max_length=20),
        ),
        migrations.AddField(
            model_name='matcheditem',
            name='found_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='api.item'),
        ),
        migrations.AddField(
            model_name='matcheditem',
            name='lost_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='api.item'),
        ),
        migrations.RemoveField(
            model_name='potentialmatch',
            name='found_item',
        ),
        migrations.RemoveField(
            model_name='potentialmatch',
            name='lost_item',
        ),
        migrations.DeleteModel(
            name='VerificationEvidence',
        ),
        migrations.DeleteModel(
            name='VerificationRequest',
        ),
        migrations.AddConstraint(
            model_name='matcheditem',
            constraint=models.UniqueConstraint(fields=('lost_item', 'found_item'), name='unique_matched_lost_found_pair'),
        ),
        migrations.DeleteModel(
            name='PotentialMatch',
        ),
    ]
